### ISSUE TITLE
How to customize the download path

### ISSUE THREAD

**Issue by q200892907** [781flyingdutchman/background_downloader#293]
How to customize the download path
For example, I want to put the desktop version in the download directory and the mobile version in the external storage directory.

**Comment by 781flyingdutchman** [comment]
Please read the [documentation](https://pub.dev/packages/background_downloader#specifying-the-location-of-the-file-to-download-or-upload).

**Comment by q200892907** [comment]
Incorrect download location when windows is set to root

For example: C:\Users\xxx\Downloads

**Comment by 781flyingdutchman** [comment]
Can you share what the task.filePath() output is in your example?

**Comment by q200892907** [comment]
> Can you share what the task.filePath() output is in your example?

The print result is InstallationDirectory/Users\xxx\Downloads\xxx.txt

**Comment by q200892907** [comment]
> > Can you share what the task.filePath() output is in your example?
> 
> The print result is InstallationDirectory/Users\xxx\Downloads\xxx.txt

@781flyingdutchman Have you reproduced it? Do you have a solution?

**Comment by 781flyingdutchman** [comment]
Sorry, haven't gotten to it as I'm busy with some other things, and don't have an ready Windows setup. But, I reopened it because I do want to reproduce and fix this bug.

**Comment by starfreck** [comment]
> How to customize the download path For example, I want to put the desktop version in the download directory and the mobile version in the external storage directory.

@q200892907  Maybe this can help you, You can navigate and create files anywhere in the file system as long as you have the permissions.  I haven't tested it on Windows yet.

```Dart
...

class Download {
  String url;
  Directory? storagePath;

  Download({required this.url, required this.storagePath});
}

...

// Entry point
static Future<String?> downloadImage(String url) async {
    late Directory? appDir;
    if (Platform.isLinux) {
      appDir = await getDownloadsDirectory();
      appDir = await Directory('${appDir!.path}/../Pictures/Wallpapers')
          .create(recursive: true);
    } else if (Platform.isAndroid) {
      appDir = await _requestStoragePermission();
      appDir = await Directory('${appDir!.path}/Wallpapers')
          .create(recursive: true);
    }

    return await _download(Download(url: url, storagePath: appDir));
}

...

static Future<Directory?> _requestStoragePermission() async {
    PermissionStatus permissionResult =
        await Permission.manageExternalStorage.request();
    if (permissionResult == PermissionStatus.granted) {
      return Directory('/storage/emulated/0/Pictures');
    } else {
      return await getApplicationDocumentsDirectory();
    }
}
  
...

static Future<String?> _download(Download downloadTask) async {
    final path = downloadTask.storagePath!.path;
    final url = downloadTask.url.replaceAll("_480", "");
    final fileName = downloadTask.url.split("/").last;
    final task = DownloadTask(
      url: url,
      filename: fileName,
      directory: path,
      baseDirectory: BaseDirectory.root, // This must be root
      updates: Updates.statusAndProgress,
      requiresWiFi: true,
      retries: 5,
      allowPause: true,
    );

    final result = await FileDownloader().download(task,
        onProgress: (progress) => print('Progress: ${progress * 100}%'),
        onStatus: (status) => print('Status: $status'));

    switch (result.status) {
      case TaskStatus.complete:
        return '$path/$fileName';
      default:
        return null;
    }
}

...
```

**Comment by q200892907** [comment]
@781flyingdutchman 
Involving segmentation and splicing, your above code only solves the splicing, and does not use the provided splicing method

**Comment by 781flyingdutchman** [comment]
Thanks for alerting me to the issue. I've implemented a more comprehensive approach

**Comment by q200892907** [comment]
@781flyingdutchman After testing on Windows using version 8.5.5, the location is still incorrect. Please use the windows platform to test that only the splicing address is correct. The file download address has nothing to do with the splicing address.

**Comment by 781flyingdutchman** [comment]
Let's move the discussion to new issue #375
